param([string]$InstallDir,[string]$SourceRef='main')
$ErrorActionPreference='Stop'
$StateRoot=Join-Path $env:LOCALAPPDATA 'D-Predict';$LogDir=Join-Path $StateRoot 'logs';$BootstrapLog=Join-Path $LogDir 'bootstrap.log';$UiLog=Join-Path $LogDir 'bootstrap-ui.log';New-Item -ItemType Directory -Force -Path $LogDir|Out-Null
Add-Type -AssemblyName System.Windows.Forms;Add-Type -AssemblyName System.Drawing
function Write-UiLog([string]$Message){"$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') $Message"|Add-Content -Path $UiLog -Encoding UTF8}
function Get-LatestPhase{if(-not(Test-Path $BootstrapLog)){return 'Preparing D-Predict setup...'};try{$x=Get-Content $BootstrapLog -Tail 80|Where-Object{"$_".Contains('==>')}|Select-Object -Last 1;if($x){return($x-replace '^.*==>\s*','').Trim()}}catch{};return 'Working...'}
$form=New-Object System.Windows.Forms.Form;$form.Text='D-Predict Setup';$form.StartPosition='CenterScreen';$form.FormBorderStyle='FixedDialog';$form.MaximizeBox=$false;$form.MinimizeBox=$true;$form.ClientSize=New-Object System.Drawing.Size(720,455);$form.BackColor=[System.Drawing.Color]::FromArgb(10,25,38);$form.ForeColor=[System.Drawing.Color]::White
$header=New-Object System.Windows.Forms.Panel;$header.Dock='Top';$header.Height=112;$header.BackColor=[System.Drawing.Color]::FromArgb(11,43,67)
$title=New-Object System.Windows.Forms.Label;$title.Text='D-Predict';$title.Font=New-Object System.Drawing.Font('Segoe UI Semibold',25,[System.Drawing.FontStyle]::Bold);$title.Location=New-Object System.Drawing.Point(30,20);$title.AutoSize=$true
$subtitle=New-Object System.Windows.Forms.Label;$subtitle.Text='Decision Intelligence Terminal  •  Initializing your local environment';$subtitle.Font=New-Object System.Drawing.Font('Segoe UI',10);$subtitle.ForeColor=[System.Drawing.Color]::FromArgb(190,210,225);$subtitle.Location=New-Object System.Drawing.Point(33,66);$subtitle.AutoSize=$true;$header.Controls.AddRange(@($title,$subtitle))
$caption=New-Object System.Windows.Forms.Label;$caption.Text='SETUP IN PROGRESS';$caption.Font=New-Object System.Drawing.Font('Segoe UI Semibold',9,[System.Drawing.FontStyle]::Bold);$caption.ForeColor=[System.Drawing.Color]::FromArgb(110,190,230);$caption.Location=New-Object System.Drawing.Point(34,137);$caption.AutoSize=$true
$phase=New-Object System.Windows.Forms.Label;$phase.Text='Preparing D-Predict setup...';$phase.Font=New-Object System.Drawing.Font('Segoe UI Semibold',14,[System.Drawing.FontStyle]::Bold);$phase.Location=New-Object System.Drawing.Point(32,162);$phase.Size=New-Object System.Drawing.Size(650,34)
$detail=New-Object System.Windows.Forms.Label;$detail.Text='Configuring prerequisites, runtime components and local services.';$detail.Font=New-Object System.Drawing.Font('Segoe UI',10);$detail.ForeColor=[System.Drawing.Color]::FromArgb(185,198,210);$detail.Location=New-Object System.Drawing.Point(34,200);$detail.Size=New-Object System.Drawing.Size(650,42)
$progress=New-Object System.Windows.Forms.ProgressBar;$progress.Style='Marquee';$progress.MarqueeAnimationSpeed=22;$progress.Location=New-Object System.Drawing.Point(34,250);$progress.Size=New-Object System.Drawing.Size(650,10)
$elapsed=New-Object System.Windows.Forms.Label;$elapsed.Text='Elapsed: 00:00';$elapsed.Font=New-Object System.Drawing.Font('Segoe UI',9);$elapsed.ForeColor=[System.Drawing.Color]::FromArgb(145,165,180);$elapsed.Location=New-Object System.Drawing.Point(34,270);$elapsed.AutoSize=$true
$logButton=New-Object System.Windows.Forms.Button;$logButton.Text='View setup log';$logButton.FlatStyle='Flat';$logButton.FlatAppearance.BorderColor=[System.Drawing.Color]::FromArgb(75,105,125);$logButton.BackColor=[System.Drawing.Color]::FromArgb(18,39,55);$logButton.ForeColor=[System.Drawing.Color]::White;$logButton.Location=New-Object System.Drawing.Point(34,315);$logButton.Size=New-Object System.Drawing.Size(130,34);$logButton.Add_Click({if(Test-Path $BootstrapLog){Start-Process notepad.exe -ArgumentList ('"'+$BootstrapLog+'"')}else{[System.Windows.Forms.MessageBox]::Show('The setup log will appear here as soon as the bootstrap starts.','D-Predict Setup')|Out-Null}})
$footer=New-Object System.Windows.Forms.Label;$footer.Text='Please keep this window open. Administrator permission may be requested by Windows.';$footer.Font=New-Object System.Drawing.Font('Segoe UI',9);$footer.ForeColor=[System.Drawing.Color]::FromArgb(145,165,180);$footer.Location=New-Object System.Drawing.Point(34,370);$footer.Size=New-Object System.Drawing.Size(650,30);$form.Controls.AddRange(@($header,$caption,$phase,$detail,$progress,$elapsed,$logButton,$footer))
$start=Get-Date;$completed=$false;$p=$null
try{$powershell=Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe';$script=Join-Path $InstallDir 'bootstrap-windows.ps1';$args=@('-NoProfile','-ExecutionPolicy','Bypass','-WindowStyle','Hidden','-File',('"'+$script+'"'),'-InstallDir',('"'+$InstallDir+'"'),'-InstallerMode','-SkipChecks','-RefreshSource');if($SourceRef){$args+=@('-SourceRef',('"'+$SourceRef+'"'))};$p=Start-Process -FilePath $powershell -ArgumentList $args -WorkingDirectory $InstallDir -WindowStyle Hidden -PassThru;Write-UiLog "Bootstrap process started. PID=$($p.Id)"}catch{Write-UiLog "ERROR: $($_.Exception.Message)";[System.Windows.Forms.MessageBox]::Show(('D-Predict could not start its setup engine.'+[Environment]::NewLine+[Environment]::NewLine+$_.Exception.Message),'D-Predict Setup')|Out-Null;exit 1}
$timer=New-Object System.Windows.Forms.Timer;$timer.Interval=500;$timer.Add_Tick({if($p){try{$p.Refresh()}catch{}};$s=(Get-Date)-$start;$elapsed.Text=('Elapsed: {0:00}:{1:00}' -f [int]$s.TotalMinutes,$s.Seconds);$q=Get-LatestPhase;if($q){$phase.Text=$q};if($p -and $p.HasExited){$timer.Stop();$progress.Style='Continuous';$progress.Value=100;if($p.ExitCode -eq 0){$completed=$true;$caption.Text='SETUP COMPLETE';$caption.ForeColor=[System.Drawing.Color]::FromArgb(90,210,150);$phase.Text='D-Predict is ready.';$detail.Text='Your local environment has been configured successfully. You can now launch D-Predict.';$footer.Text='Setup complete.';Start-Sleep -Milliseconds 700;$form.Close()}else{$caption.Text='SETUP NEEDS ATTENTION';$caption.ForeColor=[System.Drawing.Color]::FromArgb(245,170,90);$phase.Text='Setup could not be completed.';$detail.Text='Open the setup log for the exact failure and use D-Predict Repair & Check to retry.';$footer.Text="Setup log: $BootstrapLog";$logButton.Text='Open setup log';[System.Windows.Forms.MessageBox]::Show(('D-Predict setup did not complete successfully.'+[Environment]::NewLine+[Environment]::NewLine+'Open the setup log to see the exact failure.'),'D-Predict Setup')|Out-Null}}})
$form.Add_FormClosing({if($p -and -not $p.HasExited -and -not $completed){$_.Cancel=$true;[System.Windows.Forms.MessageBox]::Show('Setup is still running. Please wait for D-Predict setup to finish.','D-Predict Setup')|Out-Null}});$timer.Start();[void]$form.ShowDialog();$timer.Stop();if($p -and -not $p.HasExited){exit 1};if($p -and $p.ExitCode -ne 0){exit $p.ExitCode};exit 0