const API_BASE = import.meta.env.VITE_API_BASE_URL ?? "http://127.0.0.1:4100";
const RESEARCH_BASE = import.meta.env.VITE_RESEARCH_BASE_URL ?? "http://127.0.0.1:4200";

export type LocalHealth = { ok: boolean; database?: string; time?: string };
export type MarketOverview = { ok: boolean; symbol: string; timestamp: string | null; collectedAt?: string | null; open: number | null; high: number | null; low: number | null; close: number | null; volume: number | null; previousClose?: number | null; change?: number | null; changePercent?: number | null; source?: string; status?: "LIVE" | "CACHED" | "STALE" | "OFFLINE" };
export type Instrument = { symbol: string; exchange: string; lotSize: number; isActive: boolean; name?: string | null; providerSymbol?: string | null; instrumentType?: string | null; source?: string; observations?: number; lastMarketTimestamp?: string | null; lastCollectedAt?: string | null };
export type PriceBar = { timestamp: string; open: number; high: number; low: number; close: number; volume: number | null };
export type TargetTiming = { expectedSeconds?: number; p25Seconds?: number; p50Seconds?: number; p75Seconds?: number; probability?: number; status?: string; samples?: number; resolution?: string };
export type TradeTarget = { price: number; probability: number; return?: number; timing?: TargetTiming };
export type TradeThesis = { signal?: string; decision?: string; direction?: "LONG" | "SHORT" | "FLAT"; entryPrice?: number; expectedReturn?: number; horizon?: string; targets?: TradeTarget[]; stop?: { price: number; probability?: number; return?: number; timing?: TargetTiming }; riskRewardToTarget1?: number; probability?: number; confidence?: number; distributionStatus?: string; tradeThesisVersion?: string };
export type Signal = { id: string; symbol: string; timestamp: string; strategyVersion: string; modelVersion: string; direction: "BULLISH" | "BEARISH" | "NEUTRAL"; confidence: number; regime: string | null; reasonCodes: string[]; parameters: Record<string, unknown>; tradeThesis?: TradeThesis | null };
export type OptionRow = { expiry_date: string; strike: number; option_type: "CE" | "PE"; timestamp: string; ltp: number | null; bid: number | null; ask: number | null; oi: number | null; oiChange: number | null; iv: number | null };
export type ForecastBand = { day: number; p10: number; p25: number; median: number; p75: number; p90: number };
export type Forecast = { symbol: string; spot: number; dailyVolatility: number; daysOfHistoryUsed: number; horizonDays: number; paths: number; probabilityAboveSpot: number; probabilityBelowSpot: number; expectedValue: number; expectedReturn: number; forecastRange: { low: number; high: number }; bands: ForecastBand[]; strategy: { direction: "LONG" | "SHORT" | "FLAT"; action: "WAIT" | "STAGED_ENTRY"; rationale: string; positionSizing: string; invalidation: string }; actionSuggestions?: string[]; limitations: string[]; status: string };
export type ResearchArticle = { title: string; url: string; source: string; publishedAt: string | null; language?: string; domain?: string; sourceType: "news" | "market"; score: number; stance: "BULLISH" | "BEARISH" | "NEUTRAL" };
export type ResearchResult = { symbol: string; companyName: string | null; asOf: string; direction: "BULLISH" | "BEARISH" | "MIXED"; confidence: number; evidenceScore: number; agreement: number; articles: ResearchArticle[]; themes: string[]; risks: string[]; publicDisclosureLinks: { label: string; url: string }[]; disclaimer: string };
export type IPOInput = { companyName: string; symbol?: string; revenue?: number; revenueGrowth?: number; ebitda?: number; pat?: number; issuePrice?: number; postIssueShares?: number; freshIssue?: number; ofs?: number; debt?: number; cash?: number; roe?: number; roce?: number; sourceUrls?: string[] };
export type IPOAnalysis = { score: number; verdict: "ATTRACTIVE" | "WATCH" | "CAUTION"; valuationScore: number; businessScore: number; structureScore: number; metrics: { pe: number | null; enterpriseValue: number | null; evEbitda: number | null; ebitdaMargin: number | null; profitMargin: number | null; freshIssueRatio: number | null }; risks: string[]; methodology: string; disclaimer: string };
export type PaperOptionTrade = { id: string; symbol: string; expiry_date: string; strike: number; option_type: "CE" | "PE"; side: "BUY" | "SELL"; status: "OPEN" | "CLOSED"; lots: number; lot_size: number; quantity: number; entry_price: number; entry_bid: number | null; entry_ask: number | null; entry_ltp: number | null; entry_quote_timestamp: string; entry_timestamp: string; current_price: number | null; current_quote_timestamp: string | null; unrealized_pnl: number; realized_pnl: number | null; exit_price: number | null; exit_timestamp: string | null; exit_reason: string | null };
export type PaperPosition = { symbol: string; quantity: number; averagePrice: number; realizedPnl: number; currentPrice: number | null; currentTimestamp: string | null; unrealizedPnl: number | null };
export type PaperOrder = { id: string; symbol: string; side: "BUY" | "SELL" | "HOLD"; quantity: number; fillPrice: number | null; notional: number; realizedPnl: number; fillTimestamp: string | null; status: "FILLED" | "REJECTED" | "RECORDED"; note: string; rationale: string; signalSnapshot: Record<string, unknown>; createdAt: string };
export type PaperState = { ok: boolean; mode: "PAPER_RESEARCH"; account: null | { id: number; startingCapital: number; cash: number; realizedPnl: number; unrealizedPnl: number; equity: number; returnPct: number; openPositions: number; updatedAt: string }; positions: PaperPosition[]; orders: PaperOrder[]; marketStatus?: string; disclaimer: string };
export type PaperAnalytics = { ok: boolean; periodDays: number; since: string; summary: { actions: number; trades: number; winningTrades: number; winRate: number | null; realizedPnl: number; notional: number }; bySymbol: Array<{ symbol: string; actions: number; buys: number; sells: number; realizedPnl: number; notional: number }>; byAction: Array<{ side: "BUY" | "SELL" | "HOLD"; actions: number; realizedPnl: number; averageClosedPnl: number }>; byModelDirection: Array<{ direction: string; actions: number; realizedPnl: number; winningTrades: number }>; disclaimer: string };
export type Coverage = { symbol: string; timeframe: string; status: "FRESH" | "STALE" | "NO_DATA"; observations: number; firstTimestamp: string | null; lastTimestamp: string | null; lastCollectedAt: string | null; source: string | null; ageSeconds: number | null };
export type Performance = { symbol: string; period: string; timeframe: string; requestedDays: number; availableDays: number; coverage: number; metrics: { status: string; observations: number; startingPrice?: number; endingPrice?: number; absoluteReturn?: number; percentageReturn?: number; cagr?: number; volatility?: number; maxDrawdown?: number; bestDay?: number; worstDay?: number; positiveDayRatio?: number } };
export type WatchlistItem = { symbol: string; position: number; note: string | null; price: number | null; timestamp: string | null; status: "AVAILABLE" | "NO_DATA" };
export type MarketPick = { symbol: string; name?: string | null; spot: number; expectedReturn: number; netExpectedReturn: number; confidence: number; horizon: string; dailyVolatility: number; momentum20d: number; momentum60d: number; maxDrawdown60d: number; dataDays: number; dataAsOf: string; dataStatus: "CURRENT" | "CLOSED_LAST_SESSION"; score: number; reasons: string[]; risks: string[] };
export type PredictionPerformance = { periodDays: number; generatedAt: string; metrics: { scoredPredictions: number; pendingPredictions: number; accuracy: number | null; balancedAccuracy: number | null; directionalAccuracy: number | null; logLoss: number | null; brier: number | null; calibrationError: number | null; meanExpectedReturn: number | null; meanRealizedReturn: number | null; returnMae: number | null }; byHorizon: Array<{ horizon: string; scoredPredictions: number; accuracy: number | null; directionalAccuracy: number | null; logLoss: number | null; pendingPredictions: number }> };
export type LivePrediction = { ok: boolean; symbol: string; timestamp: string; horizon: "1d" | "3d" | "5d"; prediction: "DOWN" | "FLAT" | "UP"; probabilities: { DOWN: number; FLAT: number; UP: number }; expected_return: number; confidence: number; probability_margin: number; return_interval: { p10: number; p50: number; p90: number }; probability_net_positive: number; calibration_status: "CALIBRATED" | "UNCALIBRATED"; prediction_status: "PROMOTION_READY" | "ABSTAIN"; action_status: "ACTIONABLE_LONG" | "ACTIONABLE_SHORT" | "WATCH_FLAT" | "WATCH_LOW_EDGE" | "ABSTAIN_MODEL_GATE"; action_reasons: string[]; promotion_checks: Record<string, boolean>; oos_metrics: { accuracy: number; majority_baseline: number; log_loss: number; directional_accuracy: number | null }; model_version: string; training_cutoff: string; validation_oos_examples: number };

async function json<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); if (!response.ok) { const body = await response.json().catch(() => null) as { error?: string; message?: string } | null; throw new Error(body?.message ?? body?.error ?? `API returned ${response.status}`); } return response.json() as Promise<T>; }
export async function getLocalHealth(signal?: AbortSignal): Promise<LocalHealth> { return json<LocalHealth>(`${API_BASE}/health`, { signal }); }
export function localApiBaseUrl() { return API_BASE; }
export async function getMarketOverview(symbol = "NIFTY", signal?: AbortSignal): Promise<MarketOverview | null> { const payload = await json<MarketOverview>(`${API_BASE}/api/market/${encodeURIComponent(symbol)}/overview`, { signal }); return payload.ok ? payload : null; }
export async function getLiveQuote(symbol = "NIFTY", signal?: AbortSignal): Promise<MarketOverview | null> { const payload = await json<MarketOverview>(`${API_BASE}/api/market/${encodeURIComponent(symbol)}/live`, { signal }); return payload.ok ? payload : null; }
export async function getInstruments(signal?: AbortSignal): Promise<Instrument[]> { const payload = await json<{ instruments: Instrument[] }>(`${API_BASE}/api/instruments`, { signal }); return payload.instruments; }
export async function searchInstruments(query: string, signal?: AbortSignal): Promise<Instrument[]> { const payload = await json<{ instruments: Instrument[] }>(`${API_BASE}/api/instruments/discover?q=${encodeURIComponent(query)}`, { signal }); return payload.instruments; }
export async function addInstrument(instrument: Pick<Instrument, "symbol" | "exchange" | "lotSize" | "name" | "providerSymbol" | "instrumentType"> | string): Promise<Instrument> { const normalized = typeof instrument === "string" ? { symbol: instrument.trim().toUpperCase(), exchange: instrument.trim().toUpperCase().endsWith(".BO") ? "BSE" : "NSE", lotSize: 1, name: null, providerSymbol: instrument.trim().toUpperCase(), instrumentType: "EQUITY" } : instrument; const payload = await json<{ instrument: Instrument }>(`${API_BASE}/api/instruments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ symbol: normalized.symbol, exchange: normalized.exchange, lotSize: normalized.lotSize, name: normalized.name ?? null, providerSymbol: normalized.providerSymbol ?? normalized.symbol, instrumentType: normalized.instrumentType ?? "EQUITY" }) }); return payload.instrument; }
export async function getMarketHistory(symbol: string, timeframeOrSignal: string | AbortSignal = "1d", signal?: AbortSignal): Promise<PriceBar[]> { const timeframe = typeof timeframeOrSignal === "string" ? timeframeOrSignal : "1d"; const requestSignal = typeof timeframeOrSignal === "string" ? signal : timeframeOrSignal; const payload = await json<{ rows?: PriceBar[] }>(`${API_BASE}/api/market/${encodeURIComponent(symbol)}/history?timeframe=${encodeURIComponent(timeframe)}&limit=120`, { signal: requestSignal }); return payload.rows ?? []; }
export async function getCoverage(symbol: string, timeframe = "1d", signal?: AbortSignal): Promise<Coverage> { return json<Coverage>(`${API_BASE}/api/market/${encodeURIComponent(symbol)}/coverage?timeframe=${encodeURIComponent(timeframe)}`, { signal }); }
export async function getPerformance(symbol: string, period = "1M", timeframe = "1d", signal?: AbortSignal): Promise<Performance> { return json<Performance>(`${API_BASE}/api/market/${encodeURIComponent(symbol)}/performance?period=${encodeURIComponent(period)}&timeframe=${encodeURIComponent(timeframe)}`, { signal }); }
export async function getWatchlist(signal?: AbortSignal): Promise<WatchlistItem[]> { const payload = await json<{ items: WatchlistItem[] }>(`${API_BASE}/api/watchlist`, { signal }); return payload.items; }
export async function addToWatchlist(symbol: string, note?: string): Promise<WatchlistItem> { const payload = await json<{ item: WatchlistItem }>(`${API_BASE}/api/watchlist`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ symbol, note }) }); return payload.item; }
export async function removeFromWatchlist(symbol: string): Promise<void> { await json(`${API_BASE}/api/watchlist/${encodeURIComponent(symbol)}`, { method: "DELETE" }); }
export async function getLatestSignal(symbol: string, signal?: AbortSignal): Promise<Signal | null> { const payload = await json<{ ok: boolean; signal?: Signal | null }>(`${API_BASE}/api/signals/latest?symbol=${encodeURIComponent(symbol)}`, { signal }); if (!payload.ok || !payload.signal) return null; const signalRow = payload.signal; const parameters = signalRow.parameters ?? {}; const embedded = parameters.tradeThesis ?? parameters.trade_thesis; return { ...signalRow, tradeThesis: signalRow.tradeThesis ?? (embedded as TradeThesis | null | undefined) ?? null }; }
export async function getOptionChain(symbol: string, signal?: AbortSignal): Promise<OptionRow[]> { const payload = await json<{ rows: OptionRow[] }>(`${API_BASE}/api/options/chain?symbol=${encodeURIComponent(symbol)}`, { signal }); return payload.rows; }
export async function placeOptionPaperOrder(input: { symbol: string; expiry: string; strike: number; optionType: "CE" | "PE"; side: "BUY" | "SELL"; lots: number }): Promise<{ id: string; entryPrice: number }> { const payload = await json<{ order: { id: string; entryPrice: number } }>(`${API_BASE}/api/shadow/paper-orders`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); return payload.order; }
export async function getOptionPaperTrades(): Promise<PaperOptionTrade[]> { const payload = await json<{ trades: PaperOptionTrade[] }>(`${API_BASE}/api/shadow/paper-trades`); return payload.trades; }
export async function closeOptionPaperTrade(id: string): Promise<{ realizedPnl: number; exitPrice: number }> { return json<{ realizedPnl: number; exitPrice: number }>(`${API_BASE}/api/shadow/paper-trades/${encodeURIComponent(id)}/close`, { method: "POST" }); }
export async function getForecast(symbol: string, horizonOrSignal: number | AbortSignal = 5, signal?: AbortSignal): Promise<Forecast | null> { const horizon = typeof horizonOrSignal === "number" ? horizonOrSignal : 5; const requestSignal = typeof horizonOrSignal === "number" ? signal : horizonOrSignal; const payload = await json<Forecast & { ok?: boolean }>(`${API_BASE}/api/forecast?symbol=${encodeURIComponent(symbol)}&horizon=${Math.max(1, Math.min(30, Math.round(horizon)))}`, { signal: requestSignal }); return payload.ok === false ? null : payload; }
export async function getPaperState(signal?: AbortSignal): Promise<PaperState> { return json<PaperState>(`${API_BASE}/api/paper/state`, { signal }); }
export async function createPaperAccount(startingCapital: number): Promise<void> { await json(`${API_BASE}/api/paper/account`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ startingCapital }) }); }
export async function placePaperOrder(input: { symbol: string; side: "BUY" | "SELL" | "HOLD"; quantity: number; note?: string }): Promise<{ order: PaperOrder; cash: number; message: string }> { return json(`${API_BASE}/api/paper/orders`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); }
export async function getPaperAnalytics(days = 90, signal?: AbortSignal): Promise<PaperAnalytics> { return json<PaperAnalytics>(`${API_BASE}/api/paper/analytics?days=${Math.max(1, Math.min(3650, Math.round(days)))}`, { signal }); }
export function paperExportUrl(days = 3650): string { return `${API_BASE}/api/paper/export.csv?days=${Math.max(1, Math.min(3650, Math.round(days)))}`; }
export async function getMarketScan(limit = 5, signal?: AbortSignal): Promise<{ picks: MarketPick[]; excluded: Array<{ symbol: string; reason: string }>; asOf: string; methodology: string; disclaimer: string }> { return json(`${API_BASE}/api/market/scan?limit=${Math.max(1, Math.min(5, Math.round(limit)))}`, { signal }); }
export async function getPredictionPerformance(days = 30, signal?: AbortSignal): Promise<PredictionPerformance> { return json<PredictionPerformance>(`${API_BASE}/api/predictions/performance?days=${Math.max(1, Math.min(365, Math.round(days)))}`, { signal }); }
export async function getLivePrediction(symbol: string, horizon: 1 | 3 | 5 = 1, signal?: AbortSignal): Promise<LivePrediction | null> { const payload = await json<LivePrediction & { ok?: boolean }>(`${API_BASE}/api/predictions/live?symbol=${encodeURIComponent(symbol)}&horizon=${horizon}d`, { signal }); return payload.ok === false ? null : payload; }
export async function getResearch(symbol: string, signal?: AbortSignal): Promise<ResearchResult> { const payload = await json<{ research: ResearchResult }>(`${RESEARCH_BASE}/api/research/${encodeURIComponent(symbol)}`, { signal }); return payload.research; }
export async function analyzeIPO(input: IPOInput, signal?: AbortSignal): Promise<IPOAnalysis> { const payload = await json<{ analysis: IPOAnalysis }>(`${API_BASE}/api/ipo/analyze`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input), signal }); return payload.analysis; }
